#! /bin/bash
# Distributed Tools - dtools - dtcli
# Copyright (C) 2008 Andrés J. Díaz <ajdiaz@connectical.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

${DEBUG:+set -x}
DTOOLS_LIB="${DTOOLS_LIB:-/usr/lib/dtools}"
LC_ALL=C; LANG=C; export LANG LC_ALL
cap () { tput "$1" 2>/dev/null >/dev/null; }

# Define colors if capability is present in tty and if -N option is no
# present in command line.
if cap colors && ${opt_N:-true}; then
	H=$'\e[0;1m'
	N=$'\e[0;0m'
	R=$'\e[31;1m'
	G=$'\e[32;1m'
fi


echo "${G}*${N} dtools CLI client"
echo "${G}*${N}  environment: ${@:-NULL}"
echo "${G}*${N}  to exit press ^D or type :exit"
echo "${G}*${N}  for help type :help"


DTOOLS_PROMPT="${DTOOLS_PROMPT:-"${H}>${N} "}"
while echo -en "$DTOOLS_PROMPT" && read -e line; do
	case "$line" in
		:help)
			echo $"This is the interactive mode of dt. You can"
			echo $"run commands here, depends on environment."
			echo $"The command passed to dt will be the"
			echo $"environment plus typed command. For example"
			echo $"if environment is exp:.*, and typed command is"
			echo $"ssh echo a, then dt runs exp:.* ssh echo a in"
			echo $"command line"
			echo
			echo $"There are some especial commands, begins with ':'"
			echo $" * :exit, :quit, :bye -> exit from cli."
			echo $" * :env [new env]     -> print environment or set new"
			echo $"                         if environment is 'NULL', then"
			echo $"                         environment is deleted"
			echo
			continue;;
		:exit|:quit|:bye) exit 0;;
		:env*) 
			if [ -z "${line#:env}" ]; then
				echo "Environment: ${@:-NULL}"
			elif [ "${line#:env}" == " NULL" ]; then
				set -- 
			else
				set -- ${line#:env}
			fi
			continue;;

	esac
	if [ $# -ne 0 ] ; then
		./dt "$@" $line &
	else
		./dt $line &
	fi
	wait
done




