.TH dt  "1" "2008-12-30" ""
.SH NAME
dtdb \- the dtools database

.SH DESCRIPTION
The dt(1) script works over a special database file (or even using any other
pattern which restore data from external source), this file has the
following format, per line:

[user@]<hostname/ip[:port]>[|[user@]<proxyhost/proxyip[:port]>] [tags]+

Where

.TP
.B user
is a user to connect to hostname, if not present use the local user.

.TP
.B hostname
is the hostname or IP address of the server

.TP
.B port
is the TCP port to connect to using SSH protocol, if not present using
default one.

.TP
.B proxyhost
is a host to use as SSH proxy, that means that dtools will connect to this
host and, from there to the final host (the hostname parameter).

.TP
.B tags
is a white separated list of tags for this host. The tags can be any
alphanumeric string without spaces, commas or any other symbol.

.SH EXAMPLES

.TP
An entry for localhost with user root, tagged with "local" and "desktop"
tags.
.B root@localhost local desktop

.TP
An entry for a host in LAN with IP address 10.2.3.4 which is reacheable only
from host 10.1.1.1, tagged with tags "remote" and "proxy"
.B 10.2.3.4|10.1.1.1 remote proxy

.SH FILES

.TP
.B ~/.dtdb
This file is used as master host database for \fPdt\fP.

.SH SEE ALSO
ssh(1), ssh\-keyscan(1), dtcli(1), dtstatus(1), dthost(1), dtdb(5)

.SH AUTHOR
Andres J. Diaz <ajdiaz@connectical.com>

